version: '3.6'
services:

  viewer:
    image: ohif/viewer:v3.7.1.10058
    container_name: viewer
    depends_on:
      - orthanc
    restart: always
    ports:
      - '80:80'
    networks:
      - frontend
      - backend
    volumes:
      - ${VIEWER_CONFIG:-./config/viewer.js}:/usr/share/nginx/html/app-config.js:ro
      - ${NGINX_DEFAULT_CONF:-./config/nginx.conf}:/etc/nginx/conf.d/default.conf:ro

  orthanc:
    image: osimis/orthanc:20.2.0
    container_name: orthanc
    depends_on:
      - postgres
    restart: always
    networks:
      - frontend
      - backend
    volumes:
      - ${ORTHANC_DB:-./orthanc_db}:/var/lib/orthanc/db
      - ${ORTHANC_CONFIG:-./config/orthanc.json}:/etc/orthanc/orthanc.json:ro
    environment:
      - DW_ENABLED=true
    command: /etc/orthanc/orthanc.json

  postgres:
    image: postgres:12.1
    container_name: postgres
    networks:
      - backend
    volumes:
      - ${POSTGRES_DATA_MNT:-/pg_data/data}:${PGDATA:-/var/lib/postgresql/data}
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-pgpassword}
      - PGDATA=${PGDATA:-/var/lib/postgresql/data}
      - POSTGRES_DB=orthanc

networks:
  frontend:
  backend: